"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_project_env(path: Path):
    try:
        raw = path.read_text(encoding='utf-8')
    except Exception:
        return

    # DEBUG는 나중에 정의되므로 환경변수로 직접 확인
    _debug = os.environ.get('DEBUG', 'False') == 'True'

    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        if '=' not in s:
            continue

        k, v = s.split('=', 1)
        key = (k or '').strip()
        # 허용된 환경변수: AI + Sheets + DB/보안 (실서비스 하드닝)
        allowed_keys = {
            'AI_BACKEND', 'API_TIMEOUT_MS',
            'FC_GOOGLE_SHEET_CSV_URL', 'MASTER_DATA_CSV_URL', 'OUTBOUND_GOOGLE_SHEET_URL',
            'GOOGLE_SHEETS_API_KEY',
            'DEBUG', 'SECRET_KEY', 'DJANGO_SECRET_KEY',
            'ALLOWED_HOSTS', 'CORS_ALLOW_ALL_ORIGINS', 'CORS_ALLOWED_ORIGINS',
            'DESTRUCTIVE_API_KEY',
            'VF_WRITE_TOKEN', 'VF_PRINT_TOKEN', 'REGION_DIR',
            'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT',
        }
        allowed_prefixes = ('ANTHROPIC_', 'OLLAMA_', 'OPENROUTER_', 'AI_', 'DB_')
        import sys
        if _debug and ('GOOGLE' in key or 'MASTER_DATA' in key or 'OUTBOUND' in key):
            print(f'[DEBUG] Found {key} in allowed_keys: {key in allowed_keys}', file=sys.stderr)
        if not (any(key.startswith(p) for p in allowed_prefixes) or key in allowed_keys):
            if _debug:
                print(f'[DEBUG] Skipping key: {key}', file=sys.stderr)
            continue

        value = (v or '').strip().strip('"').strip("'")
        import sys
        if _debug and key in allowed_keys:
            print(f'[DEBUG] Key {key} in allowed, value={repr(value[:50] if len(value) > 50 else value)}, key in os.environ: {key in os.environ}', file=sys.stderr)
        # .env.local always overrides; base .env only fills missing keys
        is_local = path.name.endswith('.local')
        if key and value and (is_local or key not in os.environ):
            os.environ[key] = value
            if _debug:
                print(f'[DEBUG] Set {key} = {value[:50]}', file=sys.stderr)


_load_project_env(BASE_DIR.parent / '.env')
_load_project_env(BASE_DIR / '.env')
# 폴더별 .env.local 로딩 (.env.local이 있으면 우선 적용)
try:
    _load_project_env(BASE_DIR / '.env.local')
    _load_project_env(BASE_DIR / 'backend/.env.local')
except Exception:
    pass  # .env.local이 없으면 무시하고 계속 진행


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: env 우선, 없으면 기존 개발용 키 유지 (실서비스 중단 방지)
SECRET_KEY = (
    os.environ.get("DJANGO_SECRET_KEY")
    or os.environ.get("SECRET_KEY")
    or "django-insecure-*b1@6n%61-q1ho6p_z#-aqyadphr7$&_7f=##++b!vaetilu%p"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# comma-separated hosts; default '*' keeps current LAN/dev behavior
_allowed = (os.environ.get("ALLOWED_HOSTS") or "*").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()] or ["*"]

# Silence models.W042 warnings and use BigAutoField by default for auto-created primary keys.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Upload limits (large multi-xlsx uploads for inventory baseline)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB

# Optional: protect full-wipe APIs when set (see sales_api.api_guards)
DESTRUCTIVE_API_KEY = (os.environ.get("DESTRUCTIVE_API_KEY") or "").strip()

# 제품배치도 스냅샷 쓰기 토큰: 설정 시 POST/restore에 X-VF-Token 헤더 검증, 미설정 시 무검증(사내망 기본)
VF_WRITE_TOKEN = (os.environ.get("VF_WRITE_TOKEN") or "").strip()

# 원격 무음 인쇄 토큰 (2026-09-06): POST /api/print 은 X-VF-Token == VF_PRINT_TOKEN 일 때만 허용.
# 미설정 시 /api/print 는 503 반환 (물리 출력이라 무검증 허용 금지). GET /api/print/status 는 토큰 불필요.
VF_PRINT_TOKEN = (os.environ.get("VF_PRINT_TOKEN") or "").strip()


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "sales_api",
    "departure",
    "truck_freight",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS Middleware (Top)
    "django.middleware.security.SecurityMiddleware",
    # 대용량 JSON (마스터 목록 등) 전송 압축 — Accept-Encoding: gzip 시 적용
    # (요청 처리 상단 → 응답 시 맨 마지막에 압축)
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS: default allow-all. Set CORS_ALLOW_ALL_ORIGINS=False + CORS_ALLOWED_ORIGINS to lock down.
_cors_all = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "True").strip().lower()
CORS_ALLOW_ALL_ORIGINS = _cors_all in ("1", "true", "yes", "")
if not CORS_ALLOW_ALL_ORIGINS:
    _cors_origins = (os.environ.get("CORS_ALLOWED_ORIGINS") or "").strip()
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = []

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', 'vf_db'),
        "USER": os.environ.get('DB_USER', 'postgres'),
        "PASSWORD": os.environ.get('DB_PASSWORD', 'postgres'),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
        "OPTIONS": {
            # "connect_timeout": 10,
        }
    },
    "old_sqlite": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'sales_api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
