# Generated by Django 5.2.11 on 2026-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("hoche", models.IntegerField(db_index=True)),
                ("plate", models.CharField(blank=True, default="", max_length=50)),
                (
                    "driver_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "driver_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("ton", models.CharField(blank=True, default="5T", max_length=20)),
                (
                    "original_ton",
                    models.CharField(blank=True, default="5T", max_length=20),
                ),
                ("time", models.CharField(blank=True, default="", max_length=20)),
                ("plt", models.IntegerField(default=0)),
                ("hub", models.CharField(blank=True, default="", max_length=100)),
                ("is_new", models.BooleanField(default=False)),
                ("slip_no", models.CharField(blank=True, default="", max_length=100)),
                ("barcode", models.CharField(blank=True, default="", max_length=100)),
                ("last_seen", models.CharField(blank=True, default="-", max_length=50)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "seal_left_wing",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "seal_right_wing",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "seal_back_door",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "departure_records",
                "ordering": ["date", "hoche"],
                "unique_together": {("date", "hoche")},
            },
        ),
    ]
