# Generated by Django 5.2.12 on 2026-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("hoche", models.IntegerField(db_index=True)),
                ("plate", models.CharField(blank=True, default="", max_length=50)),
                ("kind", models.CharField(blank=True, default="LS", max_length=20)),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("ok", models.BooleanField(default=True)),
                ("printer", models.CharField(blank=True, default="", max_length=100)),
                ("client_ip", models.CharField(blank=True, default="", max_length=50)),
                ("results", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "departure_print_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
