# Generated by Django 5.2.12 on 2026-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckFreight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[("파렛트", "파렛트"), ("박스", "박스")],
                        default="파렛트",
                        max_length=10,
                    ),
                ),
                ("freight_fee", models.IntegerField(default=0)),
                (
                    "driver_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "invoice_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("입금", "입금"),
                            ("미입금", "미입금"),
                            ("확인중", "확인중"),
                            ("", "미입력"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "truck_freights",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["date"], name="truck_freig_date_f481ff_idx"),
                    models.Index(
                        fields=["invoice_type"], name="truck_freig_invoice_29c6f7_idx"
                    ),
                ],
            },
        ),
    ]
