# Generated by Django 6.0 on 2025-12-08 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboundRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("outbound_date", models.DateField(db_index=True)),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "sales_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("box_quantity", models.IntegerField(blank=True, null=True)),
                ("unit_count", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("client", models.CharField(blank=True, default="", max_length=255)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("status", models.CharField(default="완료", max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outbound_records",
                "indexes": [
                    models.Index(
                        fields=["outbound_date", "category"],
                        name="outbound_re_outboun_e10067_idx",
                    )
                ],
            },
        ),
    ]
