# Generated by Django 6.0 on 2025-12-09 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_sources",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("category", models.CharField(default="기타", max_length=100)),
                ("current_stock", models.IntegerField(default=0)),
                ("minimum_stock", models.IntegerField(default=0)),
                ("status", models.CharField(default="충분", max_length=50)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("last_restock", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_items",
            },
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="outboundrecord",
            name="sales_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
    ]
