# Generated by Django 5.2.9 on 2025-12-20 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0003_delivery_and_baco_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceiptUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_receipt_uploads',
            },
        ),
        migrations.CreateModel(
            name='InventoryBaselineUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(db_index=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_count', models.IntegerField(default=0)),
                ('file_names', models.JSONField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_barcodes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_baseline_uploads',
                'indexes': [models.Index(fields=['as_of_date', 'uploaded_at'], name='inventory_b_as_of_d_633fce_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBaselineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('quantity_box', models.IntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_api.inventorybaselineupload')),
            ],
            options={
                'db_table': 'inventory_baseline_items',
                'indexes': [models.Index(fields=['barcode'], name='inventory_b_barcode_a4849b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_datetime', models.DateTimeField(db_index=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('quantity_box', models.IntegerField(default=0)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_api.inventoryreceiptupload')),
            ],
            options={
                'db_table': 'inventory_receipt_items',
                'indexes': [models.Index(fields=['barcode', 'receipt_date'], name='inventory_r_barcode_cdc0b3_idx')],
            },
        ),
    ]
