# Generated by Django 5.2.9 on 2025-12-20 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0004_inventoryreceiptupload_inventorybaselineupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sku_id', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('min_stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barcode_master',
            },
        ),
        migrations.AddIndex(
            model_name='barcodemaster',
            index=models.Index(fields=['barcode'], name='barcode_mas_barcode_0c93ab_idx'),
        ),
    ]
