# Generated by Django 5.2.9 on 2025-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0005_barcode_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('product_name_eng', models.TextField(blank=True, default='')),
                ('mold_number', models.CharField(blank=True, default='', max_length=255)),
                ('color1', models.CharField(blank=True, default='', max_length=255)),
                ('color2', models.CharField(blank=True, default='', max_length=255)),
                ('default_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_specs',
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('machine_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('mold_number', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('product_name_eng', models.TextField(blank=True, default='')),
                ('color1', models.CharField(blank=True, default='', max_length=255)),
                ('color2', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_quantity', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_logs',
            },
        ),
        migrations.RenameIndex(
            model_name='barcodemaster',
            new_name='barcode_mas_barcode_2a6700_idx',
            old_name='barcode_mas_barcode_0c93ab_idx',
        ),
        migrations.AddIndex(
            model_name='productionlog',
            index=models.Index(fields=['date', 'machine_number'], name='production__date_1cd5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlog',
            index=models.Index(fields=['date', 'product_name'], name='production__date_7102d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.UniqueConstraint(fields=('date', 'machine_number', 'mold_number', 'product_name', 'color1', 'color2'), name='uniq_productionlog_key'),
        ),
    ]
