# Generated by Django 5.2.9 on 2025-12-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0006_masterspec_productionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodemaster',
            name='lifecycle_status',
            field=models.CharField(blank=True, db_index=True, default='active', max_length=20),
        ),
    ]
