# Generated by Django 5.2.9 on 2025-12-25 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0009_inventoryreceiptitem_unique_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('order_no', models.CharField(db_index=True, max_length=100)),
                ('order_status', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_no', models.CharField(blank=True, default='', max_length=100)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('confirmed_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inbound_order_lines',
            },
        ),
        migrations.CreateModel(
            name='InboundOrderUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(choices=[('vf_xlsx', 'VF 발주서 업로드.xlsx'), ('unreceived_csv', '발주서 미입고 물량.csv')], db_index=True, max_length=20)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_parsed', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '대기'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inbound_order_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_mode', models.CharField(choices=[('exclude', '제외'), ('include', '포함')], default='exclude', max_length=20)),
                ('statuses', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inbound_policies',
            },
        ),
        migrations.RenameIndex(
            model_name='deliveryspecialnote',
            new_name='delivery_sp_date_064231_idx',
            old_name='delivery_sp_date_31d2d3_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryspecialnote',
            new_name='delivery_sp_date_d95330_idx',
            old_name='delivery_sp_date_pr_8f6d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryspecialnote',
            new_name='delivery_sp_date_df8bd3_idx',
            old_name='delivery_sp_date_ba_1c1d59_idx',
        ),
        migrations.AlterField(
            model_name='masterspec',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='inboundorderupload',
            index=models.Index(fields=['-uploaded_at'], name='inbound_ord_uploade_a52cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundorderupload',
            index=models.Index(fields=['file_type'], name='inbound_ord_file_ty_296f9f_idx'),
        ),
        migrations.AddField(
            model_name='inboundorderline',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_api.inboundorderupload'),
        ),
        migrations.AddIndex(
            model_name='inboundorderline',
            index=models.Index(fields=['barcode'], name='inbound_ord_barcode_22c03f_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundorderline',
            index=models.Index(fields=['order_no'], name='inbound_ord_order_n_fd02bd_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundorderline',
            index=models.Index(fields=['barcode', 'order_no'], name='inbound_ord_barcode_409a12_idx'),
        ),
    ]
