# Generated by Django 5.2.9 on 2026-01-18 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0010_inboundorderline_inboundorderupload_inboundpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCInboundRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbound_date', models.DateField(db_index=True)),
                ('sku_id', models.CharField(db_index=True, max_length=100)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('logistics_center', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fc_inbound_records',
                'indexes': [models.Index(fields=['inbound_date', 'category'], name='fc_inbound__inbound_2951ca_idx'), models.Index(fields=['inbound_date', 'logistics_center'], name='fc_inbound__inbound_c5c698_idx')],
            },
        ),
    ]
