# Generated by Django 5.2.10 on 2026-01-18 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0011_fcinboundrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCInboundFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_duplicate', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'fc_inbound_file_uploads',
                'ordering': ['-upload_date'],
            },
        ),
    ]
