# Generated by Django 5.2.10 on 2026-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0012_fcinboundfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterspec',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterspec',
            name='category_lg',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='masterspec',
            name='category_md',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='masterspec',
            name='sku_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
