# Generated by Django 5.2.10 on 2026-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0013_masterspec_barcode_masterspec_category_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcinboundrecord',
            name='supply_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
