# Generated by Django 5.2.12 on 2026-04-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0014_fc_supply_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_number", models.CharField(db_index=True, max_length=20)),
                ("user_pin", models.CharField(max_length=64)),
                ("user_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "machine_users",
                "indexes": [
                    models.Index(
                        fields=["machine_number"], name="machine_use_machine_710858_idx"
                    )
                ],
                "unique_together": {("machine_number", "user_name")},
            },
        ),
        migrations.CreateModel(
            name="MachinePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("machine_number", models.CharField(db_index=True, max_length=20)),
                ("product_name", models.CharField(max_length=255)),
                ("product_name_eng", models.TextField(blank=True, default="")),
                (
                    "mold_number",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("color1", models.CharField(max_length=100)),
                ("color2", models.CharField(blank=True, default="", max_length=100)),
                ("unit", models.CharField(default="BOX", max_length=20)),
                ("quantity", models.IntegerField(default=0)),
                ("unit_quantity", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "임시저장"),
                            ("recommended", "추천"),
                            ("applied", "적용됨"),
                            ("cancelled", "취소됨"),
                        ],
                        db_index=True,
                        default="recommended",
                        max_length=20,
                    ),
                ),
                ("ai_reason", models.TextField(blank=True, default="")),
                ("outbound_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans",
                        to="sales_api.machineuser",
                    ),
                ),
            ],
            options={
                "db_table": "machine_plans",
                "indexes": [
                    models.Index(
                        fields=["date", "machine_number"],
                        name="machine_pla_date_9b422f_idx",
                    ),
                    models.Index(
                        fields=["machine_number", "status"],
                        name="machine_pla_machine_22e5b1_idx",
                    ),
                ],
            },
        ),
    ]
