# Generated by Django 5.2.12 on 2026-04-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0015_add_machine_user_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineuser",
            name="employee_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="machineuser",
            index=models.Index(
                fields=["employee_number"], name="machine_use_employe_195e75_idx"
            ),
        ),
    ]
