# Generated by Django 5.2.12 on 2026-04-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0016_add_employee_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionlog',
            name='uniq_productionlog_key',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.UniqueConstraint(fields=('date', 'machine_number', 'mold_number', 'product_name', 'color1', 'color2', 'unit'), name='uniq_productionlog_key'),
        ),
    ]
