# Generated by Django 5.2.13 on 2026-04-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0017_remove_productionlog_uniq_productionlog_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period', models.CharField(choices=[('daily', '일별'), ('weekly', '주간'), ('monthly', '월간')], default='daily', max_length=10)),
                ('summary', models.JSONField(default=dict)),
                ('chart_data', models.JSONField(default=dict)),
                ('table_data', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('source_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outbound_analysis',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'period'], name='outbound_an_date_9e1a48_idx')],
            },
        ),
    ]
