# Generated by Django 5.2.12 on 2026-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0018_add_outbound_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("color_name", models.CharField(max_length=100)),
                (
                    "color_name_eng",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("client", models.CharField(blank=True, default="", max_length=255)),
                (
                    "representative_product",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "master_colors",
                "ordering": ["sort_order", "color_code"],
            },
        ),
        migrations.CreateModel(
            name="MasterMold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mold_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_name_eng",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product_name_th",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("weight_grams", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "master_molds",
                "ordering": ["sort_order", "mold_number"],
            },
        ),
        migrations.CreateModel(
            name="MasterUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("unit_name", models.CharField(max_length=100)),
                ("unit_description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "master_units",
                "ordering": ["sort_order", "unit_code"],
            },
        ),
        migrations.CreateModel(
            name="ProductUnitSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("color_code", models.CharField(blank=True, default="", max_length=50)),
                ("unit", models.CharField(blank=True, default="BOX", max_length=20)),
                ("unit_quantity", models.IntegerField(default=0)),
                ("boxes_per_pallet", models.IntegerField(default=40)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_unit_specs",
                "indexes": [
                    models.Index(
                        fields=["product_name", "color_code"],
                        name="product_uni_product_4b0918_idx",
                    )
                ],
                "unique_together": {("product_name", "color_code", "unit")},
            },
        ),
    ]
