# Generated by Django 5.2.11 on 2026-06-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0019_mastercolor_mastermold_masterunit_productunitspec"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundrecord",
            name="purchase_price",
            field=models.IntegerField(
                blank=True, default=0, help_text="매입가(단가, 원)", null=True
            ),
        ),
    ]
