# Generated by Django 5.2.11 on 2026-06-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0020_outboundrecord_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_cost",
            field=models.IntegerField(
                blank=True, default=0, help_text="매입단가(원)", null=True
            ),
        ),
    ]
