# Generated by Django 5.2.12 on 2026-06-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0021_inventoryitem_unit_cost"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionlog",
            name="uniq_productionlog_key",
        ),
    ]
