# Generated by Django 5.2.12 on 2026-06-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0022_remove_productionlog_uniq_productionlog_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productionlog",
            constraint=models.UniqueConstraint(
                fields=(
                    "date",
                    "machine_number",
                    "mold_number",
                    "product_name",
                    "color1",
                    "color2",
                    "unit",
                    "quantity",
                    "unit_quantity",
                ),
                name="uniq_productionlog_full_key",
            ),
        ),
    ]
