# Generated by Django 5.2.11 on 2026-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0023_productionlog_uniq_productionlog_full_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="outboundrecord",
            index=models.Index(
                fields=["outbound_date", "barcode"],
                name="outbound_re_outboun_2ce2cc_idx",
            ),
        ),
    ]
