# Generated by Django 5.2.12 on 2026-07-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0025_outboundrecord_is_estimated"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="outboundrecord",
            new_name="outbound_re_outboun_7cbf96_idx",
            old_name="outbound_re_outboun_est_idx",
        ),
        migrations.AddField(
            model_name="masterspec",
            name="components",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="masterspec",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="masterspec",
            name="lot_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="masterspec",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
