# Generated by Django 5.2.12 on 2026-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales_api",
            "0026_rename_outbound_re_outboun_est_idx_outbound_re_outboun_7cbf96_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="masterspec",
            name="prev_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="masterspec",
            name="price_changed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
