# Generated by Django 5.2.12 on 2026-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0027_masterspec_prev_price_masterspec_price_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterspec",
            name="is_discontinued",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True면 단종된 품목, False면 출고 진행 품목",
            ),
        ),
    ]
