# Generated by Django 5.2.12 on 2026-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0028_masterspec_is_discontinued"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterspec",
            name="is_no_outbound_3m",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True면 최근 3개월간 출고 내역이 없는 품목, False면 출고 진행 품목",
            ),
        ),
    ]
