# Generated by Django 5.2.11 on 2026-08-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0035_masterspec_finish_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventorystockadjustment",
            new_name="inventory_s_barcode_7f4a22_idx",
            old_name="inventory_s_barcode_adj_idx",
        ),
        migrations.RenameIndex(
            model_name="inventorystockadjustment",
            new_name="inventory_s_adjustm_94b042_idx",
            old_name="inventory_s_adj_date_reason_idx",
        ),
        migrations.AddField(
            model_name="masterspec",
            name="product_number",
            field=models.IntegerField(
                blank=True,
                help_text="제품 번호. 로케이션에서 파생: 320-A1-1-XXX → XXX, 320-A1-2-XXX → 2XXX (예: 320-A1-2-115 → 2115), 그 외 null. location 저장/변경 시 자동 재계산.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="masterspec",
            name="is_discontinued",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True면 단종 품목. 단종 지정/해제는 수동(마스터 UI·API)만 허용. 자동 배치·출고 동기화는 변경하지 않음.",
            ),
        ),
        migrations.AlterField(
            model_name="masterspec",
            name="is_no_outbound_3m",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="상태열 출고 진행/3개월 미출고. VF 품목: 최근 90일 실출고(Outbound) 없음. 비VF: 최근 90일 FC 입고(쿠팡 센터 납품) 없음. 단종에는 적용 안 함. update_outbound_status 로 갱신.",
            ),
        ),
        migrations.AlterField(
            model_name="masterspec",
            name="is_vf_item",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True면 VF 대상 품목. 운영 SoT=현재 DB 값. 마스터 화면·일괄수정·양식 import 로 지정/해제. 출고·재고 자동 배치로는 변경하지 않음. 카드(출고 진행/3개월 없음)는 is_vf 안에서의 상태 분할만.",
            ),
        ),
        migrations.AlterField(
            model_name="masterspec",
            name="vf_registered_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="VF 최초 지정일. 수동 VF 지정 시 비어 있으면 오늘로 채움. 해제해도 이력 유지. 자동 해제 조건으로 쓰지 않음.",
                null=True,
            ),
        ),
    ]
