# Generated by Django 5.2.12 on 2026-08-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0037_backfill_masterspec_product_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcodemaster",
            name="is_long_term_no_order",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="장기 미발주 요청 품목. 재고=0이면서 발주처 미수락 또는 생산 지연으로 즉시 입고 불가능한 품목. True면 위험 품목(critical) 집계에서 제외되고 '장기 미발주 요청 품목' 카드로 별도 관리.",
            ),
        ),
    ]
