# Generated by Django 5.2.11 on 2026-08-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_api", "0040_barcodemaster_default_inbound_limit_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDisplaySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(db_index=True, unique=True)),
                ("payload", models.TextField()),
                ("payload_hash", models.CharField(db_index=True, max_length=40)),
                ("saved_by", models.CharField(default="browser", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_display_snapshots",
                "ordering": ["-version"],
            },
        ),
    ]
